### PR TITLE
laravel 5 support added

### PR DESCRIPTION
**Pull request by abachmann**
I need Laravel 5 support.

### CODE REVIEW

**Comment by FractalizeR** [comment]
Thank you very much for PR. Looks like it is backwards compatible with L4. Is it?

**Comment by abachmann** [comment]
I recognized that the interface "Illuminate/Queue/QueueInterface" is not part of L5 anymore. In L4 this interface is not explicit referenced it just appears in the comment block. Therefore it should be backwards compatible, but i didn't tested it.

**Comment by abachmann** [comment]
I will test my changes in L4 today. If everything works as expected, I will adjust the composer.json.

**Comment by FractalizeR** [comment]
Thanks a lot for a valuable contribution.

**Comment by abachmann** [comment]
I tested my changes in L4 now. Everything works as expected and I updated the composer.json file. Your extension has saved me a lot of time. I'm happy to give something back.

**Comment by matyunin** [comment]
@abachmann thnx!

**Pull request merged**
