### PR TITLE
Implement the Queue contract.

### PR DESCRIPTION
**Pull request by ldebrouwer**
This change brings support for Laravel 5.1 to laravel-amqp.

### CODE REVIEW

**Comment by FractalizeR** [comment]
Do I understand correctly, that this will actually break support for L4?

**Comment by ldebrouwer** [comment]
Potentially. However, currently, this package doesn't work with Laravel 5.1 due the missing Contract implementation.

**Comment by FractalizeR** [comment]
Commit tagged v.2.0.1

**Comment by matyunin** [comment]
@FractalizeR, should we remove [Laravel compatibility](http://laravel.com/) badge from our README?

**Comment by FractalizeR** [comment]
Yes, I think we should.

Best regards,
Vladislav "FractalizeR" Rastrusny

... sent from mobile
22 авг. 2015 г. 9:51 пользователь "Mikhail Matyunin" <
notifications@github.com> написал:

**Pull request merged**
