### PR TITLE
Bug fix: missing priority/attempts on failed jobs. Feature: message priorities as a standard field

### PR DESCRIPTION
**Pull request by ghost**
Hi,
I have spent the last few days trying to understand what is going on inside Laravel's queue code, and your particular driver. We observed a bug where failing jobs do not preserve the attempt-count and the priority of the job. Both of these have been fixed in this commit, which mainly focuses on how laravel parses the job into JSON, and a message-priority helper. I have tried to take a light-touch approach to modifying code. 
Anyway, please have a look at the code and message me with any questions you may have. I'm happy to jump on skype too for a chat.
All the best,
Mils

### CODE REVIEW

**Review by martianoff — CHANGES_REQUESTED** [review]
you can't rename package name, it will break installation

**Review by martianoff — CHANGES_REQUESTED** [review]
also it is very hard to understand what changes you made because you changed formatting completely

**Comment by martianoff** [comment]
at the same time i don't have issues with attempts

**Comment by FractalizeR** [comment]
@foenixteam Thanks for your contribution. But could you please:

 - Keep code formatting in place because your code changes are intermixed with formatting changes
 - Keep package name in place because it will break things for many people
 - Give me until weekend to review your changes and accept PR

**Comment by foenixteam** [comment]
Apologies, I didn't even notice the formatting change, our IDE did it automagically. 
I will re-implement the changes tomorrow with correct formatting / package name, as a separate pull-request.
Thanks,

**Comment by FractalizeR** [comment]
Sure!

**Pull request closed without merging**
