### PR TITLE
Bug fix: missing priority/attempts on failed jobs. Feature: message priorities as a standard field

### PR DESCRIPTION
**Pull request by ruslanstarikov**
Hi Guys,
We have re-implemented our changes, now with correct formatting and package name. Here is some more info on what we did, and why:

Symptoms:

1) Failed jobs do not have a timeout set
We have a long-running job (1-2 days). After failing, the timeout value disappeared and the job would take the default laravel timeout of 60s. The job would then enter an infinite loop.

2) Jobs failing a result of a timeout do not have an incremented attempts number
As a result, the job would enter an infinite loop, never reaching the failed_jobs database table.

Fix:

First, a note on our motivation. Having read a few of the other drivers (beanstalk/db), it seems that Laravel treats the serialized PHP job object as "readonly". For example, 
1) beanstalk does not keep an attempts count in the message at all (it appears to be managed by the beanstalk server)
2) the database driver has a dedicated column for attempts, thereby separating attempts from the payload

We have tried to keep this metaphor. As a result, we try not to modify the "data" element of the message. Instead, all of our state lives outside the data element.

Our implementation:

Modified the AMQJob class
1) look for attempts at `{ attempts: ... }`, instead of `{ data: { attempts: ... }}`

Modified the AMQPQueue class
1) `override` laravel's default implementations of `createObjectPayload($job)` and `createStringPayload($job, $payload)`, to support `priority` and the new location of the `attempts` field (both of which are now at the top level of the JSON message)

2) Created a new `priorityMessage($job, $data)` function that will set the message priority based on the `priority` field in the message payload, else a default priority from the queue config. The following existing functions now call the `priorityMessage` function, thereby implementing priority everywhere (except for `pushRaw` since it does not interrogate the payload)

- `push($job, $data = '', $queue = null)`
- `addMessageToBatch($job, $data = '', $queue = null)`
- `later($delay, $job, $data = '', $queue = null)`

Finally:

Finally, this did not require a lot of code change, because your library is well written. So thank you :)

### CODE REVIEW

**Review by martianoff — COMMENTED** [review]
What reason of moving attempts from $body['data']['attempts'] to $body['attempts']?
Actually current implementation of attempts works well

**Comment by martianoff** [comment]
regarding 

> Failed jobs do not have a timeout set
We have a long-running job (1-2 days). After failing, the timeout value disappeared and the job would take the default laravel timeout of 60s. The job would then enter an infinite loop.

it is not correct, with current implementation it will use queue timeout and it is correct in my opinion,
for example, if you have worker running following command:

```bash
php /var/www/artisan queue:work --queue slow_jobs --timeout=3000
```

it will have initial timeout = 3000 seconds as well as failed job timeout = 3000 seconds

**Comment by milsanore** [comment]
We do not set `timeout` with the worker, because different jobs have different timeouts. 

Therefore, we set the timeout in the job class, as specified in the [laravel documentation](https://laravel.com/docs/5.5/queues#max-job-attempts-and-timeout). 

Therefore, our bug is valid, and we do not plan on implementing a timeout on the worker level.

**Comment by martianoff** [comment]
if so it should check is it set on job level or not because for guys who are using timeouts on queue level it can cause unexpected behaviour

**Comment by milsanore** [comment]
@FractalizeR please let us know if there is anything that we can clarify regarding the pull-request, we are happy to elaborate. 

Thanks as always for the excellent library,

**Comment by FractalizeR** [comment]
I've made some corrections and merged this into master. Could you guys please test current changes from master? If everything works ok, we will tag it with something.

**Comment by ruslanstarikov** [comment]
@FractalizeR hi. I have tested the dev-master and I'm happy with everything. Priority, timeout, and maxTries are all seem to persist correctly if the job is failed and retried. 

Thank you very much for such a useful library.

**Comment by FractalizeR** [comment]
You are welcome. I think we will wait about a week and if there will be no bug reports, we will make a release.

**Pull request merged**
